CREATE TABLE "auth_states" (
	"state" text PRIMARY KEY NOT NULL,
	"verifier" text NOT NULL,
	"expires_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cables" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cables_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"a_interface_id" integer NOT NULL,
	"b_interface_id" integer NOT NULL,
	"status" text DEFAULT 'connected' NOT NULL,
	"kind" text,
	"label" text,
	"description" text,
	CONSTRAINT "cables_a_interface_id_unique" UNIQUE("a_interface_id"),
	CONSTRAINT "cables_b_interface_id_unique" UNIQUE("b_interface_id")
);
--> statement-breakpoint
CREATE TABLE "device_type_interfaces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_type_interfaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_type_id" integer NOT NULL,
	"prefix" text NOT NULL,
	"count" integer DEFAULT 1 NOT NULL,
	"kind" text DEFAULT 'ethernet' NOT NULL,
	"label" text,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "device_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"manufacturer_id" integer NOT NULL,
	"model" text NOT NULL,
	"u_height" integer DEFAULT 1 NOT NULL,
	"is_full_depth" integer DEFAULT 1 NOT NULL,
	"form_factor" text,
	"width" integer,
	"description" text,
	"comments" text
);
--> statement-breakpoint
CREATE TABLE "devices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "devices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_type_id" integer NOT NULL,
	"site_id" integer,
	"location_id" integer,
	"rack_id" integer,
	"face" text,
	"position_u" integer,
	"shelf_id" integer,
	"status" text DEFAULT 'active' NOT NULL,
	"name" text NOT NULL,
	"serial" text,
	"asset_tag" text,
	"tenant_id" integer,
	"description" text,
	CONSTRAINT "devices_asset_tag_unique" UNIQUE("asset_tag")
);
--> statement-breakpoint
CREATE TABLE "interfaces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interfaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"name" text NOT NULL,
	"kind" text DEFAULT 'ethernet' NOT NULL,
	"connected" integer DEFAULT 0 NOT NULL,
	"enabled" integer DEFAULT 1 NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "locations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"site_id" integer NOT NULL,
	"parent_id" integer,
	"tenant_id" integer,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"type" text DEFAULT 'other' NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "manufacturers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "manufacturers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	CONSTRAINT "manufacturers_name_unique" UNIQUE("name"),
	CONSTRAINT "manufacturers_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "racks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "racks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"site_id" integer NOT NULL,
	"location_id" integer,
	"tenant_id" integer,
	"rack_type_id" integer,
	"name" text NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"created_at" bigint NOT NULL,
	"last_seen_at" bigint NOT NULL,
	"expires_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shelves" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelves_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rack_id" integer NOT NULL,
	"name" text,
	"face" text,
	"position_u" integer NOT NULL,
	"mount_height" integer DEFAULT 1 NOT NULL,
	"mount_usable" integer DEFAULT 0 NOT NULL,
	"reserved_height" integer DEFAULT 0 NOT NULL,
	"is_full_depth" integer DEFAULT 1 NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "site_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "site_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenant_id" integer,
	"parent_id" integer,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"comments" text
);
--> statement-breakpoint
CREATE TABLE "sites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenant_id" integer,
	"site_group_id" integer,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"comments" text,
	"physical_address" text,
	"shipping_address" text,
	CONSTRAINT "sites_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tenants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"comments" text,
	CONSTRAINT "tenants_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"password_hash" text,
	"provider" text DEFAULT 'local' NOT NULL,
	"provider_id" text,
	"role" text DEFAULT 'viewer' NOT NULL,
	"tenant_id" integer,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_provider_id_unique" UNIQUE("provider_id")
);
--> statement-breakpoint
ALTER TABLE "cables" ADD CONSTRAINT "cables_a_interface_id_interfaces_id_fk" FOREIGN KEY ("a_interface_id") REFERENCES "public"."interfaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cables" ADD CONSTRAINT "cables_b_interface_id_interfaces_id_fk" FOREIGN KEY ("b_interface_id") REFERENCES "public"."interfaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "device_type_interfaces" ADD CONSTRAINT "device_type_interfaces_device_type_id_device_types_id_fk" FOREIGN KEY ("device_type_id") REFERENCES "public"."device_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "device_types" ADD CONSTRAINT "device_types_manufacturer_id_manufacturers_id_fk" FOREIGN KEY ("manufacturer_id") REFERENCES "public"."manufacturers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_device_type_id_device_types_id_fk" FOREIGN KEY ("device_type_id") REFERENCES "public"."device_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_site_id_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_rack_id_racks_id_fk" FOREIGN KEY ("rack_id") REFERENCES "public"."racks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_shelf_id_shelves_id_fk" FOREIGN KEY ("shelf_id") REFERENCES "public"."shelves"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interfaces" ADD CONSTRAINT "interfaces_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_site_id_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_parent_id_locations_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "racks" ADD CONSTRAINT "racks_site_id_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "racks" ADD CONSTRAINT "racks_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "racks" ADD CONSTRAINT "racks_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "racks" ADD CONSTRAINT "racks_rack_type_id_device_types_id_fk" FOREIGN KEY ("rack_type_id") REFERENCES "public"."device_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shelves" ADD CONSTRAINT "shelves_rack_id_racks_id_fk" FOREIGN KEY ("rack_id") REFERENCES "public"."racks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_groups" ADD CONSTRAINT "site_groups_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_groups" ADD CONSTRAINT "site_groups_parent_id_site_groups_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."site_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sites" ADD CONSTRAINT "sites_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sites" ADD CONSTRAINT "sites_site_group_id_site_groups_id_fk" FOREIGN KEY ("site_group_id") REFERENCES "public"."site_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_states_expires_at_idx" ON "auth_states" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "cables_a_interface_id_idx" ON "cables" USING btree ("a_interface_id");--> statement-breakpoint
CREATE INDEX "cables_b_interface_id_idx" ON "cables" USING btree ("b_interface_id");--> statement-breakpoint
CREATE INDEX "cables_status_idx" ON "cables" USING btree ("status");--> statement-breakpoint
CREATE INDEX "device_type_interfaces_type_id_idx" ON "device_type_interfaces" USING btree ("device_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "device_type_interfaces_prefix_kind_idx" ON "device_type_interfaces" USING btree ("device_type_id","prefix","kind");--> statement-breakpoint
CREATE INDEX "device_types_manufacturer_id_idx" ON "device_types" USING btree ("manufacturer_id");--> statement-breakpoint
CREATE INDEX "device_types_model_idx" ON "device_types" USING btree ("model");--> statement-breakpoint
CREATE INDEX "devices_type_id_idx" ON "devices" USING btree ("device_type_id");--> statement-breakpoint
CREATE INDEX "devices_site_id_idx" ON "devices" USING btree ("site_id");--> statement-breakpoint
CREATE INDEX "devices_rack_id_idx" ON "devices" USING btree ("rack_id");--> statement-breakpoint
CREATE INDEX "devices_shelf_id_idx" ON "devices" USING btree ("shelf_id");--> statement-breakpoint
CREATE INDEX "devices_tenant_id_idx" ON "devices" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "devices_status_idx" ON "devices" USING btree ("status");--> statement-breakpoint
CREATE INDEX "devices_name_idx" ON "devices" USING btree ("name");--> statement-breakpoint
CREATE INDEX "interfaces_device_id_idx" ON "interfaces" USING btree ("device_id");--> statement-breakpoint
CREATE UNIQUE INDEX "interfaces_device_name_idx" ON "interfaces" USING btree ("device_id","name");--> statement-breakpoint
CREATE INDEX "locations_site_id_idx" ON "locations" USING btree ("site_id");--> statement-breakpoint
CREATE INDEX "locations_parent_id_idx" ON "locations" USING btree ("parent_id");--> statement-breakpoint
CREATE UNIQUE INDEX "locations_sibling_slug_idx" ON "locations" USING btree ("site_id","parent_id","slug");--> statement-breakpoint
CREATE INDEX "manufacturers_name_idx" ON "manufacturers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "racks_site_id_idx" ON "racks" USING btree ("site_id");--> statement-breakpoint
CREATE INDEX "racks_location_id_idx" ON "racks" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "racks_tenant_id_idx" ON "racks" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "racks_name_idx" ON "racks" USING btree ("name");--> statement-breakpoint
CREATE INDEX "sessions_expires_at_idx" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "shelves_rack_id_idx" ON "shelves" USING btree ("rack_id");--> statement-breakpoint
CREATE INDEX "shelves_name_idx" ON "shelves" USING btree ("name");--> statement-breakpoint
CREATE INDEX "site_groups_tenant_id_idx" ON "site_groups" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "site_groups_parent_id_idx" ON "site_groups" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "site_groups_name_idx" ON "site_groups" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "site_groups_sibling_slug_idx" ON "site_groups" USING btree ("parent_id","slug");--> statement-breakpoint
CREATE INDEX "sites_tenant_id_idx" ON "sites" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "sites_site_group_id_idx" ON "sites" USING btree ("site_group_id");--> statement-breakpoint
CREATE INDEX "sites_name_idx" ON "sites" USING btree ("name");--> statement-breakpoint
CREATE INDEX "tenants_name_idx" ON "tenants" USING btree ("name");