CREATE TABLE "tenant_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tenant_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"comments" text,
	CONSTRAINT "tenant_groups_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "tenant_group_id" integer;--> statement-breakpoint
CREATE INDEX "tenant_groups_name_idx" ON "tenant_groups" USING btree ("name");--> statement-breakpoint
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_tenant_group_id_tenant_groups_id_fk" FOREIGN KEY ("tenant_group_id") REFERENCES "public"."tenant_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tenants_tenant_group_id_idx" ON "tenants" USING btree ("tenant_group_id");