CREATE TABLE "external_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "external_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" integer,
	"external_id" text NOT NULL,
	"external_tenant_id" text,
	"state" text DEFAULT 'linked' NOT NULL,
	"method" text DEFAULT 'manual' NOT NULL,
	"created_by" integer,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "external_objects" (
	"provider" text NOT NULL,
	"object_type" text NOT NULL,
	"external_id" text NOT NULL,
	"external_tenant_id" text,
	"data" jsonb NOT NULL,
	"fetched_at" bigint NOT NULL,
	CONSTRAINT "external_objects_provider_object_type_external_id_pk" PRIMARY KEY("provider","object_type","external_id")
);
--> statement-breakpoint
CREATE TABLE "integrations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "integrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"base_url" text NOT NULL,
	"username" text NOT NULL,
	"secrets" text NOT NULL,
	"settings" jsonb NOT NULL,
	"enabled" integer DEFAULT 1 NOT NULL,
	"created_by" integer,
	"created_at" bigint NOT NULL,
	"updated_at" bigint NOT NULL,
	"last_login_ok_at" bigint,
	"last_error" text,
	CONSTRAINT "integrations_provider_unique" UNIQUE("provider")
);
--> statement-breakpoint
CREATE TABLE "sync_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"tenant_id" integer,
	"started_at" bigint NOT NULL,
	"finished_at" bigint,
	"state" text NOT NULL,
	"error" text,
	"counts" jsonb
);
--> statement-breakpoint
ALTER TABLE "external_links" ADD CONSTRAINT "external_links_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "integrations" ADD CONSTRAINT "integrations_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_runs" ADD CONSTRAINT "sync_runs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "external_links_external_idx" ON "external_links" USING btree ("provider","entity_type","external_id");--> statement-breakpoint
CREATE INDEX "external_links_entity_idx" ON "external_links" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "external_objects_tenant_idx" ON "external_objects" USING btree ("provider","object_type","external_tenant_id");--> statement-breakpoint
CREATE INDEX "sync_runs_provider_idx" ON "sync_runs" USING btree ("provider","started_at");