CREATE TABLE "device_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	CONSTRAINT "device_roles_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE INDEX "device_roles_name_idx" ON "device_roles" USING btree ("name");--> statement-breakpoint
ALTER TABLE "devices" ADD COLUMN "device_role_id" integer;--> statement-breakpoint
INSERT INTO "device_roles" ("name", "description") VALUES ('Unknown', 'Placeholder role for devices created before device roles existed.');--> statement-breakpoint
UPDATE "devices" SET "device_role_id" = (SELECT "id" FROM "device_roles" WHERE "name" = 'Unknown');--> statement-breakpoint
ALTER TABLE "devices" ALTER COLUMN "device_role_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "devices" ADD CONSTRAINT "devices_device_role_id_device_roles_id_fk" FOREIGN KEY ("device_role_id") REFERENCES "public"."device_roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "devices_device_role_id_idx" ON "devices" USING btree ("device_role_id");
