CREATE TABLE "object_changes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "object_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" bigint NOT NULL,
	"user_id" integer,
	"username" text NOT NULL,
	"request_id" text,
	"action" text NOT NULL,
	"object_type" text NOT NULL,
	"object_id" integer NOT NULL,
	"object_repr" text NOT NULL,
	"prechange_data" jsonb,
	"postchange_data" jsonb
);
--> statement-breakpoint
ALTER TABLE "object_changes" ADD CONSTRAINT "object_changes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "object_changes_created_at_idx" ON "object_changes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "object_changes_object_idx" ON "object_changes" USING btree ("object_type","object_id");