CREATE TABLE "role_permissions" (
	"role_id" integer NOT NULL,
	"permission" text NOT NULL,
	CONSTRAINT "role_permissions_role_id_permission_pk" PRIMARY KEY("role_id","permission")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	CONSTRAINT "roles_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
INSERT INTO "roles" ("name", "description") VALUES
	('Admin', 'Full access, including users, roles, integrations and logs.'),
	('Editor', 'Reads, edits and deletes inventory and catalog data.'),
	('Viewer', 'Reads inventory and catalog data.');--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission")
	SELECT "roles"."id", "p"."permission" FROM "roles"
	CROSS JOIN (VALUES ('view'), ('edit'), ('delete'), ('users.manage'), ('changelog.view'), ('audit_log.view'), ('integrations.manage')) AS "p"("permission")
	WHERE "roles"."name" = 'Admin';--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission")
	SELECT "roles"."id", "p"."permission" FROM "roles"
	CROSS JOIN (VALUES ('view'), ('edit'), ('delete'), ('changelog.view')) AS "p"("permission")
	WHERE "roles"."name" = 'Editor';--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission")
	SELECT "roles"."id", "p"."permission" FROM "roles"
	CROSS JOIN (VALUES ('view'), ('changelog.view')) AS "p"("permission")
	WHERE "roles"."name" = 'Viewer';--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "role_id" integer;--> statement-breakpoint
UPDATE "users" SET "role_id" = (
	SELECT "id" FROM "roles" WHERE "name" = CASE "users"."role"
		WHEN 'admin' THEN 'Admin'
		WHEN 'editor' THEN 'Editor'
		ELSE 'Viewer'
	END
);--> statement-breakpoint
UPDATE "users" SET "tenant_id" = NULL WHERE "role" = 'admin';--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "role_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "role";
